### ISSUE TITLE
Redirect to default action if method is not implemented

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#393]
Got myself stuck in `Foo` menu action somehow. This is the log:

```
> libretaxi@0.1.0 telegram /home/ro/work/libretaxi
> babel-node ./src/app-telegram.js

OK telegram bot is waiting for messages...
Got '🔧 Настройки' from telegram_73808030
The 'serviceAccount' property specified in the first argument to initializeApp() is deprecated and will be removed in the next major version. You should instead use the 'firebase-admin' package. See https://firebase.google.com/docs/admin/setup for details on how to get started.
Error: not implemented
    at Foo.post (/home/ro/work/libretaxi/src/action.js:81:11)
    at Foo.call (/home/ro/work/libretaxi/src/action.js:116:19)
    at exports.default.options (/home/ro/work/libretaxi/src/call-action.js:22:27)
    at then.user (/home/ro/work/libretaxi/src/app-telegram.js:52:5)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

`post` action is not implemented in `foo`. `user.state.menuLocation` is `settings`.

We shouldn't stuck anywhere. So instead of throwing `not implemented` error, redirect to `default` menu action.

**Comment by ro31337** [comment]
Add lame implementation for now: replace Foo.get with Foo.call
