### ISSUE TITLE
Fix broken master

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#407]
Latest `master` is broken. Last stable is `dcb7644505235abdad5b3c0f8e68be671ccd6bae`.

While testing on production I got the following error:

```
Got '123' from telegram_288509295
Got '12' from telegram_288509295
Error: Firebase.update failed: First argument contains undefined in property 'users.telegram_73808030.inlineValues.hash.a00e0b7a-1a40-4a01-bdfc-2fb5528ed18d.arg.driverIdentity'
    at Error (native)
    at ff (/home/ro/work/libretaxi/node_modules/firebase/database-node.js:122:67)
    at /home/ro/work/libretaxi/node_modules/firebase/database-node.js:123:166
    at ab (/home/ro/work/libretaxi/node_modules/firebase/database-node.js:45:216)
    at ff (/home/ro/work/libretaxi/node_modules/firebase/database-node.js:122:424)
    at /home/ro/work/libretaxi/node_modules/firebase/database-node.js:123:166
    at ab (/home/ro/work/libretaxi/node_modules/firebase/database-node.js:45:216)
    at ff (/home/ro/work/libretaxi/node_modules/firebase/database-node.js:122:424)
    at /home/ro/work/libretaxi/node_modules/firebase/database-node.js:123:166
    at ab (/home/ro/work/libretaxi/node_modules/firebase/database-node.js:45:216)
    at ff (/home/ro/work/libretaxi/node_modules/firebase/database-node.js:122:424)
    at /home/ro/work/libretaxi/node_modules/firebase/database-node.js:123:166
    at ab (/home/ro/work/libretaxi/node_modules/firebase/database-node.js:45:216)
    at ff (/home/ro/work/libretaxi/node_modules/firebase/database-node.js:122:424)
    at /home/ro/work/libretaxi/node_modules/firebase/database-node.js:125:168
    at ab (/home/ro/work/libretaxi/node_modules/firebase/database-node.js:45:216)
    at hf (/home/ro/work/libretaxi/node_modules/firebase/database-node.js:125:134)
    at U.h.update (/home/ro/work/libretaxi/node_modules/firebase/database-node.js:249:359)
    at User.save (/home/ro/work/libretaxi/src/stateful.js:124:15)
    at UserStateResponseHandler.call (/home/ro/work/libretaxi/src/response-handlers/user-state-response-handler.js:35:15)
    at CompositeResponseHandler.call (/home/ro/work/libretaxi/src/response-handlers/composite-response-handler.js:57:13)
    at handler.call.retVal (/home/ro/work/libretaxi/src/response-handlers/composite-response-handler.js:58:12)
```

**Comment by ro31337** [comment]
Steps to reproduce:

* Given a driver with undefined `identity` in `driver-index` menu location.
* Place order the standard way (as a passenger)

When `identity` is undefined you'll get

> Oops, can't understand that. Please try again.

on the driver side.
