### ISSUE TITLE
Fix unknown error from Telegram

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#505]
```
Unhandled rejection TypeError: Cannot read property 'statusCode' of undefined
    at request.catch.err (/home/ro/work/libretaxi/node_modules/node-telegram-bot-api/src/telegramPolling.js:148:25)
    at tryCatcher (/home/ro/work/libretaxi/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ro/work/libretaxi/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/ro/work/libretaxi/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/ro/work/libretaxi/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/ro/work/libretaxi/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/home/ro/work/libretaxi/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ro/work/libretaxi/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ro/work/libretaxi/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

Possible solution: upgrade https://github.com/yagop/node-telegram-bot-api

**Comment by ro31337** [comment]
See https://github.com/yagop/node-telegram-bot-api/issues/281

**Comment by ro31337** [comment]
Fixed temporarily, PR created for `tgfancy` library: https://github.com/GochoMugo/tgfancy/pull/11
