### ISSUE TITLE
Unable to install babel-node

### ISSUE THREAD

**Issue by mikeres0** [ro31337/libretaxi#557]
For some reason I am receiving an error message when trying to install babel-node which is required for the project.

```
λ npm install -g babel-node

> babel-node@6.5.3 postinstall C:\Users\MikeR\AppData\Roaming\npm\node_modules\babel-node
> node message.js; sleep 10; exit 1;

module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\MikeR\AppData\Roaming\npm\node_modules\babel-node\message.js;'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! babel-node@6.5.3 postinstall: `node message.js; sleep 10; exit 1;`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the babel-node@6.5.3 postinstall script 'node message.js; sleep 10; exit 1;'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the babel-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node message.js; sleep 10; exit 1;
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs babel-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls babel-node
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MikeR\AppData\Roaming\npm-cache\_logs\2017-04-28T14_34_14_197Z-debug.log
```

Any suggestions? Ps. NodeJS noob here.

Thanks in advance 👍

**Comment by ro31337** [comment]
It's hard to help with you're noob. Please record a video from the very beginning, make sure you're following GETTING-STARTED.md document. I'll tell you where it goes wrong.

**Comment by mikeres0** [comment]
Using the wrong version of python

**Comment by ali-master** [comment]
Hi @mikeres0 
`his is not babel-node. You get babel-node by installing babel-cli:`

The Babel-node package has been replaced with `babel-cli`,

**Comment by Ridd0** [comment]
Better use `npm install --save-dev babel-cli`

**Comment by ali-master** [comment]
If you are using:
```bash
npm install --save-dev babel-cli
```
Then you can use it by **npx** with the following command:
```bash
npx babel-cli
```
