### ISSUE TITLE
Investigate geocoder bug

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#567]
Anonymized production log:

```
Got '✅ Yes' from telegram_353879XXX
Got 'Driver' from telegram_353879XXX
Got '15551112233' from telegram_353879XXX
Got '🚗 Car' from telegram_353879XXX
Got 'Next' from telegram_353879XXX
Got '5551112233' from telegram_353879XXX
/home/ro/work/libretaxi/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'latitude' of undefined
    at Geocoder.geocoder.geocode (/home/ro/work/libretaxi/build/actions/decorators/lookup-address.js:131:37)
    at Geocoder.tryCatcher (/home/ro/work/libretaxi/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/home/ro/work/libretaxi/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/home/ro/work/libretaxi/node_modules/bluebird/js/release/promise.js:564:21)
    at Promise._settlePromise0 (/home/ro/work/libretaxi/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/ro/work/libretaxi/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/ro/work/libretaxi/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ro/work/libretaxi/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ro/work/libretaxi/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by ro31337** [comment]
Seems like it works well now. Bug was fixed in another story https://github.com/ro31337/libretaxi/issues/607
