### ISSUE TITLE
Fix very long console warnings

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#657]
There are some warnings in console, like:

```
{ Error: ETELEGRAM: 403 Forbidden: bot was blocked by the user
    at request.then.resp (/home/ro/work/libretaxi/node_modules/tgfancy/node_modules/node-telegram-bot-api/src/telegram.js:181:15)
    at tryCatcher (/home/ro/work/libretaxi/node_modules/tgfancy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ro/work/libretaxi/node_modules/tgfancy/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ro/work/libretaxi/node_modules/tgfancy/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ro/work/libretaxi/node_modules/tgfancy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ro/work/libretaxi/node_modules/tgfancy/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ro/work/libretaxi/node_modules/tgfancy/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ro/work/libretaxi/node_modules/tgfancy/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ro/work/libretaxi/node_modules/tgfancy/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
  code: 'ETELEGRAM',
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
```

Caused by this:

![image](https://user-images.githubusercontent.com/1477672/33159497-3c275e3a-cfc8-11e7-82a9-9c7424cd19d4.png)

Let's just catch 403 errors and use something similar to:

```es6
.catch((error) => {
  if ((error.response || {}).statusCode === 403) {
    console.log('*** bot was blocked by the user ***');
  } else {
    console.log(error);
  }
});
```

Later we must remove the user from our system (See https://github.com/contestwatcher/contestwatcher/blob/a342f804f7c6f79356b0b7030a9ad80edb4f6dfb/bot.js for example).

**Comment by Bestulo** [comment]
I still get this super long error. Can't even fix it by catching and not logging. :C
