### ISSUE TITLE
Fix Telegram 400 error

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#666]
```
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: message is not modified
    at request.then.resp (/home/ro/work/libretaxi/node_modules/node-telegram-bot-api/src/telegram.js:245:15)
    at tryCatcher (/home/ro/work/libretaxi/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ro/work/libretaxi/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ro/work/libretaxi/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ro/work/libretaxi/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ro/work/libretaxi/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ro/work/libretaxi/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ro/work/libretaxi/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ro/work/libretaxi/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Update `src/response-handlers/telegram/telegram-errors.js` to handle 400 code. We actually do not care about this code, but should handle it. It happens time to time.

**Comment by termoxin** [comment]
What's the "message"?

**Comment by ro31337** [comment]
who cares...

**Comment by aorfevre** [comment]
bump.

Can't we get that solved ? 
It is annoying and led me to unecessary investigation :(

**Comment by oneturkmen** [comment]
I want to take this one. Will update you as soon as it gets fixed.
