### ISSUE TITLE
Nothing Happens when I press start

### ISSUE THREAD

**Issue by kris-cote** [ro31337/libretaxi#668]
[settings-libretaxi.txt](https://github.com/ro31337/libretaxi/files/1512015/settings-libretaxi.txt)
The software does not work for me. I have attached my Settings, can you please tell me whats wrong? When I press start on my bot (Automatiqbot) nothing happens.

**Comment by ro31337** [comment]
Do you have any errors when you run the program? Can you paste and/or add screenshots?

**Comment by kris-cote** [comment]
There are no errors/

**Comment by kris-cote** [comment]
SyntaxError: C:/Users/Administrator/settings.js: Unexpected token, expected ; (29:9)
  27 |   constructor(overrides) {
  28 |
> 29 | Firebase connection string
     |          ^
  30 |  this.STATEFUL_CONNSTR = 'https://libretaxi-development-e4d5a.firebaseio.com/';
  31 |
  32 |
    at Parser.pp$5.raise (C:\Users\Administrator\node_modules\babel-register\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\Users\Administrator\node_modules\babel-register\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp.semicolon (C:\Users\Administrator\node_modules\babel-register\node_modules\babylon\lib\index.js:1742:38)
    at Parser.pp$1.parseExpressionStatement (C:\Users\Administrator\node_modules\babel-register\node_modules\babylon\lib\index.js:2236:8)
    at Parser.pp$1.parseStatement (C:\Users\Administrator\node_modules\babel-register\node_modules\babylon\lib\index.js:1911:17)
    at Parser.pp$1.parseBlockBody (C:\Users\Administrator\node_modules\babel-register\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseBlock (C:\Users\Administrator\node_modules\babel-register\node_modules\babylon\lib\index.js:2247:8)
    at Parser.pp$3.parseFunctionBody (C:\Users\Administrator\node_modules\babel-register\node_modules\babylon\lib\index.js:4235:22)
    at Parser.pp$3.parseMethod (C:\Users\Administrator\node_modules\babel-register\node_modules\babylon\lib\index.js:4180:8)
    at Parser.pp$1.parseClassMethod (C:\Users\Administrator\node_modules\babel-register\node_modules\babylon\lib\index.js:2583:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libretaxi@0.1.0 telegram: `babel-node ./src/app-telegram.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libretaxi@0.1.0 telegram script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ro31337** [comment]
Sorry, this is Windows, can't provide steps to fix. It looks like you missed `npm install` command, but I don't have machine where I can reproduce this bug.

**Comment by kris-cote** [comment]
Its not a windows issue. It has to be an issue with the script itself.

**Comment by ro31337** [comment]
This program should theoretically work on Windows. However, it was not tested by me. Some other folks tested, but I can't provide full support here. You can do the following:

1. Remove everything and install again, explaining your steps one by one with screenshots and full logs (feel free to gray out actual credentials).
2. or you can install Ubuntu-based Linux on virual machine like VMWare workstation (not free), VirtualBox (free) and try it there.

Thanks for understanding.

**Comment by ro31337** [comment]
No response for a long time, closing
