### ISSUE TITLE
Error while requesting service

### ISSUE THREAD

**Issue by aliferlach** [ro31337/libretaxi#673]
SyntaxError: [sprintf] unexpected placeholder
    at sprintf_parse (/home/taxi/libretaxi/node_modules/i18n/node_modules/sprintf-js/src/sprintf.js:189:23)
    at sprintf (/home/taxi/libretaxi/node_modules/i18n/node_modules/sprintf-js/src/sprintf.js:26:31)
    at vsprintf (/home/taxi/libretaxi/node_modules/i18n/node_modules/sprintf-js/src/sprintf.js:30:24)
    at postProcess (/home/taxi/libretaxi/node_modules/i18n/i18n.js:547:13)
    at Object.i18nTranslate (/home/taxi/libretaxi/node_modules/i18n/i18n.js:234:12)
    at DriverOrderNew.t (/home/taxi/libretaxi/src/action.js:119:22)
    at DriverOrderNew.call (/home/taxi/libretaxi/src/actions/menu/driver/order/new.js:84:47)
    at exports.default.options (/home/taxi/libretaxi/src/call-action.js:41:27)
    at user (/home/taxi/libretaxi/src/app-telegram.js:92:5)
    at then.user (/home/taxi/libretaxi/src/app-telegram.js:121:9)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Comment by ro31337** [comment]
Please provide steps to reproduce, more logs, screenshots. Also, output of your commands `npm -v` and `node -v`.

What are results of tests? `npm test` command?

**Comment by aliferlach** [comment]
NPM test result

npm test
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-18T19_03_15_173Z-debug.log

**Comment by aliferlach** [comment]
```
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   workfortaxi-development-credentials.json

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package-lock.json
        modified:   settings-sample.js
```
`git rev-parse HEAD
5106ca63d41dcdf019cdeed4cde8d09e271b61a1
`

**Comment by ro31337** [comment]
`ls -lah` in current directory?

**Comment by ro31337** [comment]
meanwhile, try `rm -rf ./node_nodules && rm package-lock.json && npm install`

**Comment by aliferlach** [comment]
I messed up - project end.
