### ISSUE TITLE
Another day, same error

### ISSUE THREAD

**Issue by aliferlach** [ro31337/libretaxi#674]
`SyntaxError: [sprintf] unexpected placeholder
    at Function.sprintf.parse (/home/new/libretaxi/node_modules/sprintf-js/src/sprintf.js:164:23)
    at sprintf (/home/new/libretaxi/node_modules/sprintf-js/src/sprintf.js:19:34)
    at vsprintf (/home/new/libretaxi/node_modules/sprintf-js/src/sprintf.js:174:24)
    at module.exports.postProcess (/home/new/libretaxi/node_modules/i18n/i18n.js:547:13)
    at Object.i18nTranslate (/home/new/libretaxi/node_modules/i18n/i18n.js:234:12)
    at DriverOrderNew.t (/home/new/libretaxi/src/action.js:119:22)
    at DriverOrderNew.call (/home/new/libretaxi/src/actions/menu/driver/order/new.js:84:47)
    at exports.default.options (/home/new/libretaxi/src/call-action.js:41:27)
    at user (/home/new/libretaxi/src/app-telegram.js:92:5)
    at then.e (/home/new/libretaxi/src/app-telegram.js:121:9)
    at run (/home/new/libretaxi/node_modules/core-js/modules/es6.promise.js:66:22)
    at /home/new/libretaxi/node_modules/core-js/modules/es6.promise.js:79:30
    at flush (/home/new/libretaxi/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
`

**Comment by aliferlach** [comment]
![xd](https://user-images.githubusercontent.com/34658685/34186127-2d4d29cc-e52a-11e7-8f83-dcfaf7d5ac19.PNG)
`npm test` result

**Comment by ro31337** [comment]
Can you describe the error? Seems you have tests OK (I see you changed radius only).

**Comment by aliferlach** [comment]
Well the error appear when i request a taxi.
It worked a few times then suddenly it stopped working.

**Comment by ro31337** [comment]
Because you blocked the bot. It says "bot was blocked by the user"

**Comment by aliferlach** [comment]
And how did i do that without using any command?

**Comment by aliferlach** [comment]
Anyone got a solution for this?

**Comment by ro31337** [comment]
You unblock it from Telegram app (in worst case you can create your new bot thru BotFather).

I also have a question: which language are you using? I see you have error in translations. It shouldn't be because of this, I wonder if you modified any translations.

**Comment by aliferlach** [comment]
![token](https://user-images.githubusercontent.com/34658685/34207411-9b81249c-e58a-11e7-8f1a-72210faf5b5f.PNG)

New Bot was made but still no improvement.

**Comment by ro31337** [comment]
Ah, it's a different message now. I overlooked it in last screenshot. It says "Chat not found". Go to Firebase and remove all data (keep the database itself though).

Btw, you didn't answer to translations and language. What language are you using for bot? Have you done some translations to it? (this is a different issue - sprintf one, I wonder what's causing this. Its not happening with English)

**Comment by aliferlach** [comment]
Thank you! Finally its working. I used German but that made it impossible to use the Bot.
Its working fine in English tho, i didn't do any changes to the translations. Is it possible to disable the other languages?

**Comment by ro31337** [comment]
I'm happy I was able to help. It's possible to remove other languages. See `supported-locales.js` and just comment out lines you don't need. Also, you can remove language selection menu. It's called `select-locale` blabla something. So it's possible to set default action to something different. Poke around with the code, if you won't find it in a week, I'll try to help.
